import 'package:flutter/material.dart';

const kBgColor = Color(0xff1b1b1b);
const kBgColorL1 = Color(0xff2b2b2b);
const kBgColorL2 = Color(0xff303030);
const kTextColor = Color(0xffffffff);

const String loremIpsum =
    """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed urna ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras nulla eros, efficitur ac feugiat et, lacinia id neque. Suspendisse elementum ultrices suscipit. Ut enim ligula, aliquam vitae interdum sit amet, pharetra at leo. Ut ac elit laoreet, porttitor tellus sit amet, iaculis ante. Quisque non risus quis sem viverra porttitor. Aenean posuere nulla id ipsum pharetra, quis convallis nulla imperdiet. Suspendisse eget nulla velit. Nam porta, ipsum ut aliquet vulputate, sem dui auctor tellus, id finibus diam risus at justo. Fusce sodales mauris id nisi dignissim, non consequat ligula pretium. Curabitur eget dapibus erat.

Maecenas in tortor ac lacus porttitor vulputate in id mauris. Donec vel varius purus, et consequat massa. Cras hendrerit tempor justo et finibus. Phasellus sit amet leo felis. Nunc porttitor id lectus ac finibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam rhoncus faucibus purus, non ullamcorper diam pretium vitae. Curabitur interdum dui sit amet dui elementum, at pharetra lectus iaculis. Duis mi risus, bibendum eu mauris sit amet, molestie auctor nisl.

Vestibulum non lacinia ligula, eu bibendum elit. Suspendisse eget magna nec magna pulvinar finibus. Sed a risus aliquam, rhoncus nisl vitae, mattis velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Fusce sed scelerisque quam. Sed sit amet tristique eros. Nunc ac diam sollicitudin, finibus mauris a, vehicula nunc. Etiam id leo nec tortor lacinia facilisis ac sit amet massa. Pellentesque feugiat justo semper eros fringilla, sed pellentesque quam semper. Curabitur convallis orci quam, nec pharetra felis malesuada vel. Suspendisse venenatis ac nulla ac accumsan. Suspendisse tincidunt fringilla lectus id congue. Maecenas eu quam dui. Nulla sit amet turpis vel leo imperdiet commodo at quis justo. Vestibulum fringilla libero ac eros eleifend pulvinar. Nam laoreet dolor ante.

Aliquam imperdiet scelerisque tortor, tempor consequat turpis dictum sed. Fusce tristique, nulla eget dapibus accumsan, dolor urna malesuada elit, ac euismod nisi neque quis mauris. Proin interdum metus nisl, non condimentum magna tempor sit amet. Sed et finibus orci. Vivamus euismod egestas turpis id tincidunt. Donec lacinia feugiat quam. Praesent eu ante nec arcu finibus elementum vitae vitae leo. Fusce convallis, lectus at hendrerit sollicitudin, nibh nibh facilisis justo, sed rhoncus nisl nibh non nisi. Morbi vestibulum venenatis purus vel tincidunt. Duis tempus quam eu nulla cursus, ac imperdiet elit hendrerit. Aliquam cursus lectus non erat ultricies vehicula.

Nulla sed dapibus diam, sit amet laoreet est. Vivamus pellentesque cursus magna, eu interdum eros pharetra nec. Quisque congue condimentum mi, sed auctor lacus auctor a. Phasellus tempus elit sit amet magna aliquet vestibulum. Sed volutpat libero eget lorem pellentesque sollicitudin. Curabitur ullamcorper tempor erat, a tempor neque malesuada quis. Ut pretium mollis erat convallis venenatis. Etiam et faucibus neque. Curabitur id quam faucibus lorem lobortis lobortis. Donec eu iaculis mi. Ut vulputate eget arcu ac ultricies. In scelerisque risus ac neque lacinia, vitae rutrum lorem dapibus. Ut at urna bibendum, rutrum ipsum vitae, aliquet risus. Vestibulum id tincidunt odio, id maximus quam. Aenean lobortis quam nec aliquet bibendum. Suspendisse facilisis mollis nibh, quis commodo dolor tristique nec.""";
